version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: test-env-storage
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  redis:
      image: "redis:latest"
      container_name: test-env-redis
      ports:
        - "${REDIS_PORT}:${REDIS_PORT}"
      environment:
        - REDIS_DB=${REDIS_DB}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
      command: ["redis-server", "--databases", "${REDIS_DB}"]